main_server:
    host: localhost
    port: 8000

secure_aggregator:
    host: localhost
    port: 8001

dashboard:
    host: 192.168.31.31
    port: 8002

clients:
    - 1:
        host: localhost
        port: 8003
    - 2:
        host: localhost
        port: 8004
    - 3:
        host: localhost
        port: 8005
#    - 4:
#        host: localhost
#        port: 8006
#    - 5:
#        host: localhost
#        port: 8007

